
title: Aiura's Blog
author: Aiuraa
email: none@void.site
description: > # this means to ignore newlines until "twitter_username:"
  A simple blogging post about everything i want to share to the world
  It may useful for some people but it's just personal pereference i think
  
# social links
twitter_username: aiur4a
github_username:  Aiuraa
rss: rss

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Remote settings
remote_theme:  jekyll/minima 
